# Generated by Django 2.2.8 on 2020-04-28 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 28, 14, 43, 35, 533124, tzinfo=utc))),
            ],
        ),
    ]
